input_data_path: "data/raw/heart_cleveland_upload.csv"
experiment_path: "models/boosting"
output_model_fname: "model.pkl"
fitted_transform_fname: "transform.pkl"
metric_fname: "metrics.json"
test_data_path: "data/raw/test_data.csv"
test_label_path: "data/raw/test_label.csv"
train_data_path: "data/raw/train.csv"
predict_path: "models/boosting/predicts.csv"

split_params:
  test_size: 0.3
  seed: 12

train_params:
  model_type: "Boosting"
  params:
    random_state: 12

feature_params:
  transforms:
    - transform: "StandardScaler"
      columns:
        - "age"
        - "trestbps"

    - transform: "OneHotEncoder"
      columns:
        - "cp"
        - "restecg"
        - "slope"
        - "ca"
        - "thal"

    - transform: "pass"
      columns:
        - "sex"
        - "fbs"
        - "exang"
        - "chol"
        - "thalach"
        - "oldpeak"

  target_col: "condition"